### ISSUE TITLE
Timestamp for every update

### ISSUE THREAD

**Issue by fardavide** [enrichman/covid19#4]
Please add a timestamp for every update, so it would be possible to create some charts.
Actually a timestamp is available only for the most recent update

**Comment by enrichman** [comment]
@4face-studi0 not sure on what do you mean.
The timeseries object provides you all the days with all the values.

I've updated the readme with some more information!

**Comment by fardavide** [comment]
Yes, you're right :) I've been a little confused by that `t`. W/out a deep examination I was thinking it's referencing to the total population :P
